name = "ihelper-tech"
compatibility_date = "2024-01-22"

[build]
command = "python tools/build.py"
output_dir = "build"
base_dir = "."

[site]
bucket = "./build"
entry-point = "workers-site/index.js"

[env.production]
name = "ihelper-tech-prod"
route = "ihelper.tech/*"

[env.staging]
name = "ihelper-tech-staging"
route = "staging.ihelper.tech/*"
